/**
 * Problem 2
 * http://projecteuler.net/problem=2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
var p = function (n) {
  var i,
      a = 1,
      b = 2,
      sum = 2;

  for (i = 3; i < n; i = a + b) {
    if (i % 2 === 0) sum += i;
    a = b;
    b = i;
  }

  return sum;
};

console.log(p(4000000));
